import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import { optionalPlaywright, startPrototypeStack, fetchJson, waitFor } from "./prototype-copy-test-helpers.mjs";

test("imported manual continues through writing UI, saves, reopens and exports actual article", async t => {
  if (process.env.RUN_BROWSER_E2E !== "1") { t.skip("Set RUN_BROWSER_E2E=1"); return; }
  const pw = await optionalPlaywright(t);
  if (!pw) return;
  const stack = await startPrototypeStack(t, pw);
  if (!stack) return;
  const { page, webBase, apiBase } = stack;
  await page.goto(`${webBase}/prototype`, { waitUntil: "networkidle" });
  await page.locator('.rail-btn[data-module="settings"]').click();
  await page.locator('[data-settings-item="desktop-help"]').click();
  page.once('dialog', dialog => dialog.dismiss());
  await page.locator('#settingsImportSmartNotesDemo').click();
  await waitFor(async () => assert.match(await page.locator('#settingsImportSmartNotesDemoStatus').innerText(), /已取消/));
  const missing = await fetchJson(apiBase, '/api/v1/writing-projects/WRITE-SMART-NOTES-DEMO');
  assert.equal(missing.status, 400);
  assert.match(JSON.stringify(missing.json), /writingProjectId not found/);
  page.once('dialog', dialog => dialog.accept());
  await page.locator('#settingsImportSmartNotesDemo').click();
  await waitFor(async () => assert.equal((await fetchJson(apiBase, '/api/v1/writing-projects/WRITE-SMART-NOTES-DEMO')).status, 200), 15000);
  await waitFor(async () => assert.equal(await page.locator('#settingsImportSmartNotesDemo').isEnabled(), true), 15000);
  await page.locator('.rail-btn[data-module="writing"]').click();
  await page.locator('[data-writing-sidebar-action="topics"]').click();
  const resume = page.locator('[data-writing-index-card-id="THEME-INDEX-TO-WRITING"] button');
  await waitFor(async () => assert.equal(await resume.getAttribute('data-writing-project-id'), 'WRITE-SMART-NOTES-DEMO'));
  await resume.click();
  const editor = page.locator('#writingDraftEditor:visible');
  await editor.waitFor();
  const initial = await editor.inputValue();
  assert.match(initial, /研思录使用说明/);
  assert.match(initial, /## 3\. 文摘与文献笔记/);
  assert.match(initial, /## 7\. 写作/);
  const addition = '我的体验：把阅读中的疑问组织成自己的文章。';
  await editor.fill(`${initial}\n\n${addition}`);
  await page.locator('#btnWritingSaveDraft').click();
  await waitFor(async () => {
    const project = (await fetchJson(apiBase, '/api/v1/writing-projects/WRITE-SMART-NOTES-DEMO')).json.item;
    const note = (await fetchJson(apiBase, `/api/v1/notes/${project.draft_note_id}`)).json.item;
    assert.ok(note.body.includes(addition));
  });
  await page.reload({ waitUntil: 'networkidle' });
  await page.locator('.rail-btn[data-module="writing"]').click();
  await page.locator('[data-writing-sidebar-action="topics"]').click();
  await waitFor(async () => assert.equal(await resume.getAttribute('data-writing-project-id'), 'WRITE-SMART-NOTES-DEMO'));
  await resume.click();
  await editor.waitFor();
  assert.ok((await editor.inputValue()).includes(addition));
  const out = await fs.mkdtemp(path.join(os.tmpdir(), 'yansilu-manual-export-'));
  t.after(() => fs.rm(out, { recursive: true, force: true }));
  await page.locator('#writingMoreMenu > summary').click();
  const response = page.waitForResponse(r => r.url().endsWith('/api/v1/exports/article'));
  await page.locator('#btnWritingExportArticle').click();
  await page.locator('[data-text-input-field]:visible').fill(out);
  await page.locator('[data-text-input-confirm]:visible').click();
  const exported = await (await response).json();
  assert.equal(exported.status, 'completed');
  const markdown = await fs.readFile(exported.articlePath, 'utf8');
  assert.ok(markdown.includes(addition));
  assert.match(markdown, /## 8\. 明天从哪里继续/);
});
