import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs/promises";
import { optionalPlaywright, startPrototypeStack, fetchJson, putJson } from "./prototype-copy-test-helpers.mjs";
import { createManualWritingTheme, findWritingProject } from "./prototype-writing-flow-helpers.mjs";
import { createWritingSourceFixture, captureWritingSources } from "./prototype-writing-topic-repair-flow-helpers.mjs";

test("a missing viewpoint has an actionable Chinese outline notice and clears after repair without regenerating sections", async t => {
  if (process.env.RUN_BROWSER_E2E !== "1") { t.skip("Set RUN_BROWSER_E2E=1"); return; }
  const pw = await optionalPlaywright(t);
  if (!pw) return;
  const stack = await startPrototypeStack(t, pw);
  if (!stack) return;
  const { page, apiBase, webBase } = stack, notes = await createWritingSourceFixture(stack), source = notes[0];
  assert.equal((await putJson(apiBase, `/api/v1/notes/${source.id}`, { thesis: "" })).status, 200);
  const title = "补齐判断后核对文章";
  await createManualWritingTheme(stack, notes, { title });
  const assertSourcesUnchanged = await captureWritingSources(stack, notes);
  let aiExecutions = 0;
  page.on("request", req => { if (req.method() === "POST" && new URL(req.url()).pathname === "/api/v1/writing/ai-analysis") aiExecutions++; });
  await page.locator("#btnWritingCreateScaffold").click();
  await page.locator("#writingScaffoldPanel:visible").waitFor();
  const project = await findWritingProject(stack, notes, title);
  const detail = (await fetchJson(apiBase, `/api/v1/writing-projects/${project.id}`)).json.item;
  assert.equal(detail.preflight.status, "has_gaps");
  const readScaffold = async () => (await fetchJson(apiBase, `/api/v1/draft-scaffolds/${project.scaffold_id}`)).json.item;
  const scaffold = await readScaffold(), issue = scaffold.preflight.checks.find(check => check.id === "basket_notes_missing_thesis");
  assert.equal(issue.status, "warning"); assert.deepEqual(issue.targetNoteIds, [source.id]);
  const notices = page.locator("#writingScaffoldPreview .writing-outline-source-notices");
  assert.match(await notices.innerText(), /1 条.*笔记.*补.*一句话判断/);
  assert.doesNotMatch(await notices.innerText(), /has_gaps|thesis|distillation|basket|scaffold/);
  assert.equal(await notices.locator(`[data-writing-outline-source-note="${source.id}"]`).count(), 1);
  const downloaded = page.waitForEvent("download");
  await page.locator("#writingMoreMenu > summary").click();
  await page.locator("#btnWritingExportScaffold").click();
  const markdown = await fs.readFile(await (await downloaded).path(), "utf8");
  assert.match(markdown, /待补内容：/); assert.ok(markdown.includes(`[[${source.title}]]`));
  assert.doesNotMatch(markdown, /has_gaps|basket_notes_missing_thesis|wp_[a-f0-9]+/);
  await notices.locator(`[data-writing-outline-source-note="${source.id}"]`).click();
  await page.locator("#wysiwygHost:visible").waitFor();
  assert.match(await page.locator("#wysiwygHost").innerText(), /保留中文/);
  await assertSourcesUnchanged(); assert.deepEqual(await readScaffold(), scaffold);
  const repaired = await putJson(apiBase, `/api/v1/notes/${source.id}`, { thesis: source.thesis });
  assert.equal(repaired.status, 200); assert.equal(repaired.json.item.body, source.body);
  const assertRepairedSourcesUnchanged = await captureWritingSources(stack, notes);
  await page.goto(`${webBase}/prototype`, { waitUntil: "networkidle" });
  await page.locator('.rail-btn[data-module="writing"]').click();
  await page.locator(`[data-writing-index-card-id="${project.related_index_ids[0]}"] button[data-writing-project-id="${project.id}"]`).click();
  await page.locator("#writingScaffoldPanel:visible").waitFor();
  assert.equal(await page.locator(`#writingScaffoldPreview [data-writing-outline-source-note="${source.id}"]`).count(), 0);
  const refreshed = await readScaffold();
  assert.equal(refreshed.preflight.checks.some(check => check.id === "basket_notes_missing_thesis"), false);
  assert.deepEqual(refreshed.sections, scaffold.sections); assert.equal(refreshed.id, scaffold.id);
  assert.equal((await fetchJson(apiBase, "/api/v1/writing-projects?limit=50")).json.items.length, 1);
  await assertRepairedSourcesUnchanged(); assert.equal(aiExecutions, 0);
});
