import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs/promises";
import path from "node:path";
import os from "node:os";
import { optionalPlaywright, startPrototypeStack, fetchJson, waitFor } from "./prototype-copy-test-helpers.mjs";

for (const width of [1366, 390, 320]) {
  test(`large import exposes every candidate with cross-page selection and real confirmation (${width}px)`, async t => {
    if (process.env.RUN_BROWSER_E2E !== "1") { t.skip("Set RUN_BROWSER_E2E=1"); return; }
    const pw = await optionalPlaywright(t);
    if (!pw) return;
    const stack = await startPrototypeStack(t, pw);
    if (!stack) return;
    const { page, apiBase, vaultPath } = stack;
    page.setDefaultTimeout(15000);
    const source = await fs.mkdtemp(path.join(os.tmpdir(), "yansilu-large-import-source-"));
    t.after(() => fs.rm(source, { recursive: true, force: true }));
    const destination = await fs.mkdtemp(path.join(os.tmpdir(), "yansilu-large-import-export-"));
    t.after(() => fs.rm(destination, { recursive: true, force: true }));
    const originals = new Map();
    for (let index = 1; index <= 25; index++) {
      const number = String(index).padStart(2, "0");
      originals.set(`${number}.md`, `---\ntype: permanent\ntitle: 判断 ${number}\n---\n# 判断 ${number}\n\n## 一句话论点\n第 ${number} 次阅读后，我应先说清楚问题，再检查证据是否足以支持判断。\n\n## 我的依据\n这条笔记记录第 ${number} 次练习中自己的理解，不是原文摘抄。\n`);
    }
    const quotation = "Retrieval practice strengthens long term retention more than passive rereading.";
    originals.set("26.md", `---\ntype: permanent\ntitle: 需要核对的引文\n---\n# 需要核对的引文\n\n## 一句话论点\n${quotation}\n\n## 原文\n${quotation}\n`);
    for (const [file, body] of originals) await fs.writeFile(path.join(source, file), body, "utf8");
    const unchanged = async () => {
      for (const [file, body] of originals) assert.equal(await fs.readFile(path.join(source, file), "utf8"), body);
    };
    const output = "output/playwright/core-large-import";
    await fs.mkdir(output, { recursive: true });
    const errors = [];
    page.on("pageerror", error => errors.push(error.message));
    await page.setViewportSize({ width, height: width === 1366 ? 768 : 844 });
    await page.locator('.rail-btn[data-module="settings"]').click();
    if (width === 1366) await page.locator('[data-settings-item="import-export"]').click();
    else await page.locator("#settingsMobileItemSelect").selectOption("import-export");
    await page.locator("#importPath").fill(source);
    const previewResponse = page.waitForResponse(response => response.url().includes("/imports/preview") && response.request().method() === "POST");
    await page.locator("#btnImportPreview").click();
    const preview = await (await previewResponse).json();
    assert.equal(preview.candidatePreview.permanentNotes.length, 26);
    assert.equal(preview.candidatePreview.sources.length, 26);
    assert.equal(preview.candidatePreview.literatureNotes.length, 1);
    assert.equal(preview.candidatePreview.truncated, false);
    const candidate = title => preview.candidatePreview.permanentNotes.find(item => item.title === title);
    const later = candidate("判断 13"), last = candidate("判断 25"), blocked = candidate("需要核对的引文");
    assert.equal(blocked.originalityStatus, "blocked");
    await page.locator("#btnImportConfirm:visible").waitFor();
    const pager = page.locator('[data-candidate-page-select]');
    const checkbox = id => page.locator(`.candidate-checkbox[data-candidate-id="${id}"]`);
    assert.equal(await page.locator(".candidate-checkbox").count(), 12);
    assert.equal(await page.locator(".candidate-selection-options").evaluate(node => node.open), false);
    assert.match(await page.locator("#btnImportConfirm").innerText(), /52/);
    assert.equal((await fetchJson(apiBase, "/api/v1/directories/dir_original_default/notes")).json.items.length, 0);
    await unchanged();
    await page.screenshot({ path: `${output}/first-${width}.png` });
    await page.locator('[data-candidate-action="none"]').click();
    assert.equal(await page.locator("#btnImportConfirm").isDisabled(), true);
    await pager.selectOption("5");
    assert.equal(await page.locator(".candidate-checkbox:checked").count(), 0);
    await page.locator('[data-candidate-action="all"]').click();
    assert.match(await page.locator("#btnImportConfirm").innerText(), /52/);
    assert.equal(await page.locator('[data-candidate-page="next"]').isDisabled(), true);
    await pager.selectOption("1");
    await page.locator('[data-candidate-page="next"]').focus();
    await page.keyboard.press("Enter");
    assert.equal(await pager.inputValue(), "2");
    assert.equal(await page.evaluate(() => document.activeElement?.getAttribute("data-candidate-page")), "next");
    await checkbox(later.id).focus();
    await page.keyboard.press("Space");
    assert.equal(await checkbox(later.id).isChecked(), false);
    assert.equal(await page.evaluate(() => document.activeElement?.getAttribute("data-candidate-id")), later.id);
    await pager.selectOption("3");
    await checkbox(last.id).uncheck();
    assert.equal(await checkbox(blocked.id).isDisabled(), true);
    assert.equal(await checkbox(blocked.id).isChecked(), false);
    assert.match(await page.locator("#btnImportConfirm").innerText(), /50/);
    await page.screenshot({ path: `${output}/later-${width}.png` });
    await page.locator(".candidate-selection-options summary").click();
    await page.locator('[data-candidate-filter="blocked"]').click();
    assert.equal(await page.locator(".candidate-checkbox").count(), 1);
    assert.equal(await checkbox(blocked.id).isDisabled(), true);
    assert.equal(await pager.count(), 0);
    await page.locator('[data-candidate-filter="blocked"]').click();
    assert.equal(await pager.inputValue(), "1");
    await pager.selectOption("2");
    assert.equal(await checkbox(later.id).isChecked(), false);
    await page.evaluate(() => window.__prototypeImport.renderPage());
    assert.equal(await pager.inputValue(), "2");
    assert.equal(await checkbox(later.id).isChecked(), false);
    await pager.selectOption("4");
    await page.locator('[data-candidate-page="next"]').focus();
    await page.keyboard.press("Enter");
    assert.equal(await pager.inputValue(), "5");
    assert.equal(await pager.evaluate(node => node === document.activeElement), true, "Last-page keyboard focus must remain usable");
    assert.ok(await page.locator(".candidate-checkbox").count() <= 12);
    await unchanged();
    const confirmResponse = page.waitForResponse(response => /\/imports\/[^/]+\/confirm/.test(response.url()) && response.request().method() === "POST");
    await page.locator("#btnImportConfirm").click();
    const response = await confirmResponse;
    const confirmation = await response.json();
    assert.equal(response.request().postDataJSON().overrideOriginality, undefined);
    assert.equal(response.request().postDataJSON().originalityPlan, undefined);
    assert.equal(response.request().postDataJSON().selectedCandidateIds.length, 50);
    assert.deepEqual(confirmation.result.created, { sources: 26, literatureNotes: 1, permanentNotes: 23 });
    assert.equal(confirmation.result.createdFiles.some(item => [later.id, last.id, blocked.id].includes(item.noteId)), false);
    await page.locator('#importResult .result-card[data-result-stage="confirm"]').waitFor();
    for (const item of confirmation.result.createdFiles) {
      const body = await fs.readFile(path.join(vaultPath, item.path), "utf8");
      assert.ok(body.length > 0);
    }
    const imported = preview.candidatePreview.permanentNotes.find(item => item.title === "判断 24");
    const note = (await fetchJson(apiBase, `/api/v1/notes/${imported.id}`)).json.item;
    assert.match(note.body, /第 24 次阅读/);
    assert.equal(note.authorship.user_confirmed, false);
    assert.equal(note.status, "draft");
    assert.equal(await page.locator(".result-candidates-detail").evaluate(node => node.open), false);
    await page.locator(".result-candidates-detail summary").click();
    await pager.selectOption("5");
    assert.equal(await page.locator(".result-candidates-detail").evaluate(node => node.open), true);
    await page.locator('[data-candidate-page="previous"]').focus();
    await page.keyboard.press("Enter");
    assert.equal(await pager.inputValue(), "4");
    assert.equal(await page.evaluate(() => document.activeElement?.getAttribute("data-candidate-page")), "previous");
    await page.locator(".result-skip-detail summary").click();
    await page.locator('[data-skip-focus="unselected"]').click();
    await waitFor(async () => assert.equal(await page.locator(".candidate-item").count(), 3));
    assert.equal(await page.locator(".result-candidates-detail").evaluate(node => node.open), true);
    for (const id of [later.id, last.id, blocked.id]) assert.equal(await page.locator(`.candidate-item[data-candidate-id="${id}"]`).count(), 1);
    assert.match(await page.locator(`.candidate-item[data-candidate-id="${blocked.id}"]`).innerText(), /原创性检查未通过/);
    const bounds = await page.locator("#importOperationResultModal .modal").boundingBox();
    assert.ok(bounds.x >= 0 && bounds.y >= 0 && bounds.x + bounds.width <= width + 1);
    assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true);
    await page.locator(".candidate-focus-banner").scrollIntoViewIfNeeded();
    await page.screenshot({ path: `${output}/confirmed-${width}.png` });
    await page.locator('[data-clear-candidate-focus]').focus();
    await page.keyboard.press("Enter");
    assert.equal(await pager.inputValue(), "1");
    assert.equal(await pager.evaluate(node => node === document.activeElement), true);
    await page.locator("#btnCloseImportOperationResult").click();
    await page.locator("#importWorkspaceTabExport").click();
    await page.locator("#exportTargetPath").fill(destination);
    await page.locator("#btnExportMarkdown").click();
    await page.locator('#exportResult .result-card[data-result-stage="export_markdown"]').waitFor();
    const exportedFiles = await fs.readdir(destination, { recursive: true });
    const exportedBodies = await Promise.all(exportedFiles.filter(file => file.endsWith(".md")).map(file => fs.readFile(path.join(destination, file), "utf8")));
    assert.ok(exportedBodies.some(body => body.includes("第 24 次阅读")));
    assert.equal(exportedBodies.some(body => body.includes("第 13 次阅读") || body.includes("第 25 次阅读") || body.includes("# 需要核对的引文")), false);
    await unchanged();
    assert.deepEqual(errors, []);
  });
}

test("late ordinary reading notes and long skipped receipts remain inspectable at 320px", async t => {
  if (process.env.RUN_BROWSER_E2E !== "1") { t.skip("Set RUN_BROWSER_E2E=1"); return; }
  const pw = await optionalPlaywright(t);
  if (!pw) return;
  const stack = await startPrototypeStack(t, pw);
  if (!stack) return;
  const { page, apiBase, vaultPath } = stack;
  page.setDefaultTimeout(15000);
  const source = await fs.mkdtemp(path.join(os.tmpdir(), "yansilu-large-reading-source-"));
  t.after(() => fs.rm(source, { recursive: true, force: true }));
  const originals = new Map();
  for (let index = 1; index <= 26; index++) {
    const number = String(index).padStart(2, "0");
    const body = `# 阅读记录 ${number}\n\n这是第 ${number} 次阅读留下的材料。后续再用自己的话整理观点。\n`;
    originals.set(`${number}.md`, body);
    await fs.writeFile(path.join(source, `${number}.md`), body, "utf8");
  }
  await page.setViewportSize({ width: 320, height: 844 });
  await page.locator('.rail-btn[data-module="settings"]').click();
  await page.locator("#settingsMobileItemSelect").selectOption("import-export");
  await page.locator("#importPath").fill(source);
  const previewResponse = page.waitForResponse(response => response.url().includes("/imports/preview") && response.request().method() === "POST");
  await page.locator("#btnImportPreview").click();
  const preview = await (await previewResponse).json();
  assert.equal(preview.candidatePreview.literatureNotes.length, 26);
  assert.equal(preview.candidatePreview.sources.length, 26);
  const late = preview.candidatePreview.literatureNotes[25];
  assert.match(late.title, /26/);
  const archive = preview.candidatePreview.sources.find(item => item.id === late.sourceId);
  assert.ok(archive);
  await page.locator("#btnImportConfirm:visible").waitFor();
  await page.locator('[data-candidate-action="none"]').click();
  const pager = page.locator('[data-candidate-page-select]');
  await pager.selectOption("3");
  await page.locator(`.candidate-checkbox[data-candidate-id="${late.id}"]`).check();
  await pager.selectOption("5");
  await page.locator(`.candidate-checkbox[data-candidate-id="${archive.id}"]`).check();
  assert.match(await page.locator("#btnImportConfirm").innerText(), /2\/52/);
  const confirmResponse = page.waitForResponse(response => /\/imports\/[^/]+\/confirm/.test(response.url()) && response.request().method() === "POST");
  await page.locator("#btnImportConfirm").click();
  const confirmed = await (await confirmResponse).json();
  assert.deepEqual(confirmed.result.created, { sources: 1, literatureNotes: 1, permanentNotes: 0 });
  const note = (await fetchJson(apiBase, `/api/v1/notes/${late.id}`)).json.item;
  assert.match(note.body, /第 26 次阅读/);
  assert.match(await fs.readFile(path.join(vaultPath, note.markdownPath), "utf8"), /第 26 次阅读/);
  await page.locator('#importResult .result-card[data-result-stage="confirm"]').waitFor();
  await page.locator(".result-skip-detail summary").click();
  await page.locator('[data-skip-focus="unselected"]').click();
  assert.equal(await page.locator(".result-candidates-detail").evaluate(node => node.open), true);
  assert.equal(await pager.locator("option").count(), 5);
  assert.equal(await page.locator(".candidate-item").count(), 12);
  await pager.focus();
  await pager.selectOption("5");
  assert.equal(await page.locator(".candidate-item").count(), 2);
  assert.equal(await page.locator(`.candidate-item[data-candidate-id="${late.id}"]`).count(), 0);
  assert.equal(await page.locator(".result-candidates-detail").evaluate(node => node.open), true);
  assert.equal(await pager.evaluate(node => node === document.activeElement), true);
  for (const [name, body] of originals) assert.equal(await fs.readFile(path.join(source, name), "utf8"), body);
});
