param(
  [Parameter(Mandatory = $true)]
  [string]$Name,

  [ValidateSet("feat", "fix", "docs", "chore", "spike")]
  [string]$Kind = "feat",

  [string]$Base = "main",
  [string]$Root = "",
  [int]$ApiPort = 0,
  [int]$WebPort = 0
)

$ErrorActionPreference = "Stop"

function Get-RepoRoot {
  $root = (& git rev-parse --show-toplevel 2>$null).Trim()
  if (-not $root) {
    throw "Not inside a git repository."
  }
  return $root
}

function Normalize-Slug([string]$Text) {
  $slug = $Text.ToLower() -replace "[^a-z0-9\-]", "-"
  $slug = $slug -replace "-{2,}", "-"
  return $slug.Trim("-")
}

function Read-EnvMap([string]$FilePath) {
  $map = @{}
  if (-not (Test-Path -LiteralPath $FilePath)) { return $map }

  Get-Content -Encoding UTF8 -LiteralPath $FilePath | ForEach-Object {
    $line = $_.Trim()
    if (-not $line) { return }
    if ($line.StartsWith("#")) { return }
    $parts = $line.Split("=", 2)
    if ($parts.Count -eq 2) {
      $map[$parts[0].Trim()] = $parts[1].Trim()
    }
  }
  return $map
}

function Get-UsedPorts([string]$RootDir) {
  $used = [System.Collections.Generic.HashSet[int]]::new()
  if (-not (Test-Path -LiteralPath $RootDir)) { return $used }

  Get-ChildItem -Recurse -File -LiteralPath $RootDir -Filter ".env.worktree" -ErrorAction SilentlyContinue | ForEach-Object {
    $envMap = Read-EnvMap $_.FullName
    foreach ($k in @("API_PORT", "WEB_PORT")) {
      if ($envMap.ContainsKey($k)) {
        $n = 0
        if ([int]::TryParse($envMap[$k], [ref]$n)) {
          [void]$used.Add($n)
        }
      }
    }
  }
  return $used
}

function Next-FreePort([int]$Start, [int]$Step, [System.Collections.Generic.HashSet[int]]$Used) {
  $p = $Start
  while ($Used.Contains($p)) {
    $p += $Step
  }
  return $p
}

function Ensure-Vault([string]$RepoRoot, [string]$VaultPath) {
  $template = Join-Path $RepoRoot "vault-example\yansilu-vault"
  if ((Test-Path -LiteralPath $template) -and -not (Test-Path -LiteralPath $VaultPath)) {
    New-Item -ItemType Directory -Force -Path (Split-Path -Parent $VaultPath) | Out-Null
    Copy-Item -LiteralPath $template -Destination $VaultPath -Recurse -Force
    return
  }

  New-Item -ItemType Directory -Force -Path $VaultPath | Out-Null
  foreach ($d in @(
    "notes\fleeting", "notes\literature", "notes\permanent", "notes\index", "notes\projects",
    "assets\pdf", "assets\images", "assets\audio",
    "imports\zotero", "imports\readwise", "imports\notebooklm", "imports\obsidian",
    "exports", ".yansilu"
  )) {
    New-Item -ItemType Directory -Force -Path (Join-Path $VaultPath $d) | Out-Null
  }
  if (-not (Test-Path -LiteralPath (Join-Path $VaultPath ".yansilu\settings.json"))) {
    "{}" | Set-Content -Encoding UTF8 -LiteralPath (Join-Path $VaultPath ".yansilu\settings.json")
  }
  if (-not (Test-Path -LiteralPath (Join-Path $VaultPath ".yansilu\import-map.json"))) {
    "{}" | Set-Content -Encoding UTF8 -LiteralPath (Join-Path $VaultPath ".yansilu\import-map.json")
  }
}

$repoRoot = Get-RepoRoot
$slug = Normalize-Slug $Name
if (-not $slug) { throw "Name must contain at least one letter or number." }

if ([string]::IsNullOrWhiteSpace($Root)) {
  $Root = Join-Path ([System.IO.Path]::GetDirectoryName($repoRoot)) "yansilu-wt"
}

New-Item -ItemType Directory -Force -Path $Root | Out-Null

$branch = "$Kind/$slug"
$worktreeDirName = "$Kind-$slug"
$worktreePath = Join-Path $Root $worktreeDirName

if (Test-Path -LiteralPath $worktreePath) {
  throw "Worktree path already exists: $worktreePath"
}

$null = & git -C $repoRoot show-ref --verify --quiet "refs/heads/$branch"
$branchExists = ($LASTEXITCODE -eq 0)

if ($branchExists) {
  & git -C $repoRoot worktree add "$worktreePath" "$branch"
} else {
  & git -C $repoRoot worktree add -b "$branch" "$worktreePath" "$Base"
}
if ($LASTEXITCODE -ne 0) {
  throw "git worktree add failed."
}

$usedPorts = Get-UsedPorts $Root
if ($ApiPort -le 0) {
  $ApiPort = Next-FreePort 3000 100 $usedPorts
}
[void]$usedPorts.Add($ApiPort)

if ($WebPort -le 0) {
  $offset = [math]::Floor(($ApiPort - 3000) / 100)
  $candidate = 5173 + (100 * $offset)
  while ($usedPorts.Contains($candidate)) {
    $candidate += 100
  }
  $WebPort = $candidate
}
if ($usedPorts.Contains($WebPort)) {
  throw "WebPort already in use by another worktree: $WebPort"
}

$vaultRoot = Join-Path $Root "_vaults"
$vaultPath = Join-Path (Join-Path $vaultRoot $worktreeDirName) "yansilu-vault"
Ensure-Vault $repoRoot $vaultPath

$envFile = Join-Path $worktreePath ".env.worktree"
$envLines = @(
  "# Auto generated by scripts/worktree-create.ps1",
  "WORKTREE_NAME=$worktreeDirName",
  "WORKTREE_BRANCH=$branch",
  "API_PORT=$ApiPort",
  "WEB_PORT=$WebPort",
  "API_BASE=http://localhost:$ApiPort",
  ("VAULT_PATH=" + ($vaultPath -replace "\\", "/"))
)
$envLines | Set-Content -Encoding UTF8 -LiteralPath $envFile

Write-Output "Created worktree: $worktreePath"
Write-Output "Branch: $branch"
Write-Output "Env file: $envFile"
Write-Output "API_PORT=$ApiPort WEB_PORT=$WebPort"
Write-Output "VAULT_PATH=$vaultPath"
Write-Output "Next: cd `"$worktreePath`" ; ./scripts/worktree-run-dev.ps1"
